### ISSUE TITLE
Investigate search performance

### ISSUE THREAD

**Issue by Ostrzyciel** [rdzanyM/science_points#22]
Searching for journals seems unusually slow. We should profile this, find the bottleneck and see if we can improve it somehow.

Is the issue the size of the DB or the size of the query? How will it scale?

**Comment by YuseqYaseq** [comment]
+99% of the time is spent inside this generator:
https://github.com/rdzanyM/science_points/blob/cbd4551e8790c209380742f868214a52499a768b/src/text_index/text_index.py#L130

Im not familiar with this library, do you have any suggestions how this can be improved? @Ostrzyciel

**Comment by YuseqYaseq** [comment]
Note: lowering the limit doesn't improve things because as far as I can tell most of the time only a few (<5) results are returned so the limit is never reached.

**Comment by Ostrzyciel** [comment]
Riiight. I think the main issue here is that the underlying library is written in Python, that's bound to be limiting. I don't think we have an alternative either, if we want to keep deployment complexity low. We could also try to make the index a bit smaller (different ngram settings), but we would probably lose some accuracy on the way.

The only reasonable choice that comes my mind is to instead vectorize the names and use an embedded, disk-backed vector store. But I'm not sure if we have the time to reimplement all that. :/

**Comment by YuseqYaseq** [comment]
Im closing this issue then. We can return to it if there is enough pressure from the "product owner".
