### ISSUE TITLE
Make it clear what is the default date

### ISSUE THREAD

**Issue by Ostrzyciel** [rdzanyM/science_points#27]
In case the user has not specified the date in the search criteria:
![image](https://user-images.githubusercontent.com/56843159/117777643-18937c00-b23d-11eb-81e2-b1ddd4b6dc82.png)

It is not clear what this field defaults to. The most recent date?

**Comment by rdzanyM** [comment]
![image](https://user-images.githubusercontent.com/43205483/119121958-4ee7ad00-ba2e-11eb-9d7d-5b077cafeab6.png)
