### ISSUE TITLE
Search triggering is confusing

### ISSUE THREAD

**Issue by Ostrzyciel** [rdzanyM/science_points#60]
The search can be triggered by either:
* A change in the publication type input.
* A change in the domain input.
* Clicking the search button.

Changing the query table's content does not trigger searching, which is inconsistent with the other inputs. IMO we should remove the triggers from the other inputs and leave the search button as the only trigger. I don't think triggering an update every time the query table is changed is a good idea – the app is too slow for that.

**Comment by rdzanyM** [comment]
Ok, so I tested it, and updating on table change fires only after changing the focus (not after every letter typed). So do we still want to update only on button click? @Ostrzyciel

**Comment by rdzanyM** [comment]
Personally, I prefer the 'update only on button click' variant

**Comment by Ostrzyciel** [comment]
> Personally, I prefer the 'update only on button click' variant

Yeah, me too, that makes it clearer to the user, imo.
