### ISSUE TITLE
Searching imported data doesn't work

### ISSUE THREAD

**Issue by Ostrzyciel** [rdzanyM/science_points#73]
To reproduce:
1. Click the import button, paste some content (e.g. [this](https://github.com/rdzanyM/science_points/blob/ee28373e2443819cdfa2731852cbe19c971bf57f/misc/import_test_cases/commas_and_quotes.csv)).
2. Click "Impotuj". The data should appear in the search table.
3. Click "Szukaj".
4. The results will not reflect the query.

I'm pretty sure there's something broken with state handling.

**Comment by Ostrzyciel** [comment]
The same applies to removing rows in the search table, but only if the results table is already present.

**Comment by rdzanyM** [comment]
> The same applies to removing rows in the search table, but only if the results table is already present.

Removing rows works well for me locally as well as on the deployed version

**Comment by rdzanyM** [comment]
I also fixed another bug. After clicking 'add row' button, subsequent imports were treated as 'add row' clicks.

**Comment by rdzanyM** [comment]
By the way, the fix for this issue was weird
![image](https://user-images.githubusercontent.com/43205483/119188413-ebd03780-ba7a-11eb-8d1e-be0d277ccfcf.png)
